services:
  oro_akeneo.settings.sync_products.provider:
    class: Oro\Bundle\AkeneoBundle\Settings\DataProvider\SyncProductsDataProvider

  oro_akeneo.encoder.crypter:
    class: Oro\Bundle\AkeneoBundle\Encoder\Crypter
    arguments:
      - "@oro_security.encoder.default"

  oro_akeneo.connection.client_factory:
    class: Oro\Bundle\AkeneoBundle\Client\AkeneoClientFactory
    arguments:
      - "@oro_entity.doctrine_helper"
      - "@oro_akeneo.encoder.crypter"
      - "@oro_akeneo.client_builder"

  oro_akeneo.security.acl.voter.channel:
    class: Oro\Bundle\AkeneoBundle\Acl\Voter\CategoryVoter
    arguments:
      - "@oro_entity.doctrine_helper"
    calls:
      - [setClassName, ['%oro_catalog.entity.category.class%']]
  #        tags:
  #            - { name: security.voter}

  oro_akeneo.event_subscriber.field_config:
    class: Oro\Bundle\AkeneoBundle\EventSubscriber\FieldConfigSubscriber
    tags:
      - { name: kernel.event_subscriber }

  oro_akeneo.placeholder.schema_update_filter:
    class: Oro\Bundle\AkeneoBundle\Placeholder\SchemaUpdateFilter
    public: true
    arguments:
      - "@oro_entity_config.config_manager"
      - "@oro_entity_config.helper.entity_config_provider_helper"

  oro_akeneo.form.extension.channel_type:
    class: Oro\Bundle\AkeneoBundle\Form\Extension\ChannelTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Oro\Bundle\IntegrationBundle\Form\Type\ChannelType }

  oro_akeneo.form.extension.product_type:
    class: Oro\Bundle\AkeneoBundle\Form\Extension\ProductTypeExtension
    arguments:
      - "@oro_entity_config.config_manager"
      - "@oro_entity.helper.field_helper"
    tags:
      - { name: form.type_extension, extended_type: Oro\Bundle\ProductBundle\Form\Type\ProductType }

  oro_akeneo.enum_synchronizer:
    class: Oro\Bundle\AkeneoBundle\Tools\EnumSynchronizer
    parent: oro_entity_extend.enum_synchronizer

  oro_akeneo.integration.search_builder:
    class: Oro\Bundle\AkeneoBundle\Integration\AkeneoSearchBuilder

  oro_akeneo.validator.json_validator:
    class: Oro\Bundle\AkeneoBundle\Validator\JsonValidator
    tags:
      - { name: validator.constraint_validator, alias: oro_akeneo.json_validator }

  oro_akeneo.validator.attribute_code_validator:
    class: Oro\Bundle\AkeneoBundle\Validator\AttributeCodeValidator
    tags:
      - { name: validator.constraint_validator, alias: oro_akeneo.attribute_code_validator }

  oro_akeneo.validator.alternative_identifier_validator:
    class: Oro\Bundle\AkeneoBundle\Validator\AlternativeIdentifierValidator
    tags:
      - { name: val

  oro_akeneo.validator.attribute_mapping_validator:
    class: Oro\Bundle\AkeneoBundle\Validator\AttributeMappingValidator
    tags:
      - { name: validator.constraint_validator, alias: oro_akeneo.attribute_mapping_validator }

  oro_akeneo.event_subscriber.doctrine:
    class: 'Oro\Bundle\AkeneoBundle\EventSubscriber\DoctrineSubscriber'
    calls:
      - [setContainer, ['@service_container']]
    tags:
      - { name: doctrine.event_subscriber }

  oro_akeneo.strategy.import.helper:
    class: 'Oro\Bundle\AkeneoBundle\ImportExport\Strategy\ImportStrategyHelper'
    parent: oro_importexport.strategy.import.helper
    decorates: oro_importexport.strategy.import.helper
    calls:
      - [setDoctrineHelper, ['@oro_entity.doctrine_helper']]

  oro_akeneo.async.sync_integration_processor:
    class: 'Oro\Bundle\AkeneoBundle\Async\SyncIntegrationProcessor'
    decorates: oro_integration.async.sync_integration_processor
    arguments:
      - '@doctrine'
      - '@security.token_storage'
      - '@oro_integration.processor_registry'
      - '@oro_message_queue.job.runner'
    calls:
      - [setLogger, ["@logger"]]

  oro_akeneo.async.export_contacts_status_update_processor:
    class: 'Oro\Bundle\AkeneoBundle\Async\ImportProductProcessor'
    arguments:
      - '@oro_entity.doctrine_helper'
      - '@oro_message_queue.job.runner'
      - '@security.token_storage'
      - '@logger'
      - '@oro_integration.processor_registry'
    tags:
      - { name: 'oro_message_queue.client.message_processor', topicName: 'oro.integration.akeneo.product' }

  oro_akeneo.client_builder:
    class: Oro\Bundle\AkeneoBundle\Client\AkeneoClientBuilder

  oro_akeneo.config_manager:
    class: 'Oro\Bundle\AkeneoBundle\Config\ConfigManager'
    decorates: oro_entity_config.config_manager
    parent: oro_entity_config.config_manager

  oro_akeneo.event_listener.doctrine_tag.decorator:
    class: Oro\Bundle\AkeneoBundle\EventListener\DoctrineTagEventListenerDecorator
    decorates: oro_sync.event_listener.doctrine_tag
    decoration_priority: -255
    public: true
    arguments:
      - '@oro_akeneo.event_listener.doctrine_tag.decorator.inner'

  oro_akeneo.event_listener.import_export_tags_subscriber.decorator:
    class: Oro\Bundle\AkeneoBundle\EventListener\ImportExportTagsSubscriberDecorator
    decorates: oro_tag.event_listener.import_export_tags_subscriber
    decoration_priority: -255
    public: true
    arguments:
      - '@oro_akeneo.event_listener.import_export_tags_subscriber.decorator.inner'

  oro_akeneo.event_listener.product_collection_variant_reindex_message_send_listener.decorator:
    class: Oro\Bundle\AkeneoBundle\EventListener\ProductCollectionVariantReindexMessageSendListenerDecorator
    decorates: oro_product.entity.event_listener.product_collection_variant_reindex_message_send_listener
    decoration_priority: -255
    public: true
    arguments:
      - '@oro_akeneo.event_listener.product_collection_variant_reindex_message_send_listener.decorator.inner'

  oro_akeneo.event_listener.reindex_parent_configurable_product.decorator:
    class: Oro\Bundle\AkeneoBundle\EventListener\ReindexParentConfigurableProductListenerDecorator
    decorates: oro_product.event_listener.reindex_parent_configurable_product
    decoration_priority: -255
    arguments:
      - '@oro_akeneo.event_listener.reindex_parent_configurable_product.decorator.inner'

  oro_akeneo.event_listener.additional_optional_listeners_manager:
    class: Oro\Bundle\AkeneoBundle\EventListener\AdditionalOptionalListenerManager

  oro_akeneo.job.context.aggregator.simple:
    class: 'Oro\Bundle\AkeneoBundle\Job\Context\SimpleContextAggregator'
    parent: oro_importexport.job.context.aggregator.simple
    decorates: oro_importexport.job.context.aggregator.simple

  oro_akeneo.product_unit.discovery:
    class: Oro\Bundle\AkeneoBundle\ProductUnit\ImportFromAkeneoDiscovery
    arguments:
      - '@oro_config.manager'
      - '@oro_product.provider.product_units_provider'

  oro_akeneo.product_variant.type_handler.string_type_handle:
    class: 'Oro\Bundle\AkeneoBundle\ProductVariant\TypeHandler\StringTypeHandler'
    arguments:
      - '@form.factory'

  oro_akeneo.product_variant.registry.product_variant_type_handler_factory:
    parent: oro_product.product_variant.registry.product_variant_type_handler_factory
    decorates: oro_product.product_variant.registry.product_variant_type_handler_factory
    calls:
      - [addHandler, ['@oro_akeneo.product_variant.type_handler.string_type_handle']]

  oro_akeneo.product_variant_field.field_value_handler.string_type_handler:
    class: 'Oro\Bundle\AkeneoBundle\ProductVariant\VariantFieldValueHandler\StringVariantFieldValueHandler'
    arguments:
      - '@oro_entity.doctrine_helper'

  oro_akeneo.product_variant_field.registry.product_variant_field_value_handler_registry:
    parent: oro_product.product_variant_field.registry.product_variant_field_value_handler_registry
    decorates: oro_product.product_variant_field.registry.product_variant_field_value_handler_registry
    calls:
      - [addHandler, ['@oro_akeneo.product_variant_field.field_value_handler.string_type_handler']]

  oro_akeneo.provider.serialized_field_provider:
    class: 'Oro\Bundle\AkeneoBundle\Provider\SerializedFieldProvider'
    decorates: oro_entity_config.provider.serialized_field_provider
    decoration_priority: -255
    arguments:
      - '@oro_akeneo.provider.serialized_field_provider.inner'
      - '@oro_entity_config.provider.importexport'

  oro_akeneo.provider.variant_field_provider:
    class: 'Oro\Bundle\AkeneoBundle\Provider\VariantFieldProvider'
    decorates: oro_product.provider.variant_field_provider
    arguments:
      - '@oro_akeneo.provider.variant_field_provider.inner'
      - '@oro_entity_config.manager.attribute_manager'
      - '@oro_entity_config.provider.serialized_field_provider'
